[package]
name = "embedded_support"
version = "0.1.0"
edition.workspace = true
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
debugger_ui.workspace = true
gpui.workspace = true
icons.workspace = true
log.workspace = true
project.workspace = true
serde_json.workspace = true
task.workspace = true
tasks_ui.workspace = true
ui.workspace = true
which.workspace = true
workspace.workspace = true
